version:'3.8'

services:

  mysql:
    image:mysql:latest
    container_name:mysql_container
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: mysql

  nginx:
    image:nginx:latest
    container_name:nginx_container
